import { getAllMomen } from '../db/momen';
import { getLastSiklus } from '../db/siklus';
import dayjs from 'dayjs';

export async function exportICS(): Promise<string> {
  const lines: string[] = [
    'BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Duple//EN', 'CALSCALE:GREGORIAN', 'METHOD:PUBLISH'
  ];

  const momens = await getAllMomen();
  for (const m of momens) {
    const dt = dayjs(m.tanggal).format('YYYYMMDD');
    lines.push(
      'BEGIN:VEVENT',
      `DTSTART;VALUE=DATE:${dt}`,
      `DTEND;VALUE=DATE:${dayjs(m.tanggal).add(1,'day').format('YYYYMMDD')}`,
      `SUMMARY:${m.kategori === 'anniversary' ? '💝' : '📌'} ${m.nama}`,
      `DESCRIPTION:${m.kategori} — ${m.notes || m.nama}`,
      'TRANSP:TRANSPARENT',
      'END:VEVENT'
    );
  }

  const siklus = await getLastSiklus(3);
  if (siklus.length >= 2) {
    const cycles: number[] = [];
    for (let i = 0; i < siklus.length - 1; i++) {
      const d = dayjs(siklus[i].tgl_mulai).diff(dayjs(siklus[i + 1].tgl_mulai), 'day');
      if (d > 0 && d < 50) cycles.push(d);
    }
    if (cycles.length > 0) {
      const avg = Math.round(cycles.reduce((a,b)=>a+b,0)/cycles.length);
      const nextCycle = dayjs(siklus[0].tgl_mulai).add(avg, 'day');
      const dt = nextCycle.format('YYYYMMDD');
      lines.push(
        'BEGIN:VEVENT',
        `DTSTART;VALUE=DATE:${dt}`,
        `DTEND;VALUE=DATE:${nextCycle.add(5,'day').format('YYYYMMDD')}`,
        'SUMMARY:🩸 Predicted Cycle',
        'DESCRIPTION:Predicted cycle (auto-generated by Duple)',
        'TRANSP:TRANSPARENT',
        'END:VEVENT'
      );
    }
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

export function downloadICS(ics: string) {
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `duple-calendar-${dayjs().format('YYYY-MM-DD')}.ics`;
  a.click();
}
